### ISSUE TITLE
"Upgrade required" when running npm run dev

### ISSUE THREAD

**Issue by russx2** [sjones6/remix-render-starter#1]
This is just the example I was looking for with remix and render. Thanks.

However, when I run `npm run dev` and access `localhost:8002` I just get the text string `Upgrade required` output to the browser. This smells like something prisma maybe? But I'm not too familiar with it and can't see anything obvious. Any ideas?

**Comment by russx2** [comment]
I'm dumb. It's running on port `9000`. Whoops!

**Comment by sjones6** [comment]
Glad you figured it out—that's a bit of a less usual choice. Port 3000 seems to be more common these days.

If you want to change it, change the `PORT` environment variable in your `.env` file and optionally in your `render.yaml` file.
